name: Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ALGOLIA_API_KEY: ${{ secrets.MYTESTSECRET}}
    steps:
    - run: echo "Algolia API Key $ALGOLIA_API_KEY"
    - uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: npm ci
    - run: npm run lint
    